### ISSUE TITLE
Compatibility with Empire

### ISSUE THREAD

**Issue by Alexis-Grimm** [juanosarg/AlphaBiomes#1]
Hello! Love Alpha Biomes and Alpha Animals, there is a mod called empire which provides the player with the ability to produce settlements, settlements have unique production values for different kinds of biomes, of course this means that modded biomes have a default 1.0 value for everything. This isn't very accurate, I was wondering if you would be willing to provide compatibility, its a very simple patch, if you would like I can provide it myself.

**Comment by juanosarg** [comment]
This was added a while ago :)
