### ISSUE TITLE
Crop Sprout of Agarilux Prime on Mycotic Jungle causes Crippling Lag.

### ISSUE THREAD

**Issue by SGuivenne** [juanosarg/AlphaBiomes#6]
While it was hilarious (and deeply terrifying) to get about 20 Agarilux Primes spawn in the middle of the main trader lane, this event resulted in heavy lag that made the game constantly stutter.  Presumably caused by the sheer quantity of virulent spores released by them.  This should probably be excluded from the crop sprout event, or any event really.

**Comment by juanosarg** [comment]
This should be changed on Vanilla Events Expanded, I can do nothing about it, sorry
